# JMS configurations, it is same as reading from .properties file just the syntax is different
# Spring will automatically read .yml and construct properties like guru.jms.username and so on
# It is also true if a duplicate property is found, it will be overridden, so make sure .properties and .yml have unique keys
guru:
  jms:
    username: JMS Username1
    password: jmspassword1
    url: jmsurl1

--- # it is a file separator, you can have multiple files in a single file in yaml, below file will override value for default
spring:
  profile:de
guru:
  jms:
    password: jmaspassword**in**german

# Must read from Spring documentation (you don't know how it overrides because naming convention is not there)
# In case of application.properties, contents are overridden by application-<profile-name>.properties

# In case of YAML, Multi-profile YAML Documents
# You can specify multiple profile-specific YAML documents in a single file by using a spring.profiles key to indicate when the document applies, as shown in the following example:
